# Generated by Django 4.1.4 on 2023-01-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCountVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=4, verbose_name='Год')),
                ('avgSalary', models.CharField(default='', max_length=100000, verbose_name='Количество вакансий в IT')),
                ('avgSalaryVac', models.CharField(default='', max_length=100000, verbose_name='Количество вакансий по профессии Backend-разработчик')),
            ],
            options={
                'verbose_name': 'Количество вакансий',
                'verbose_name_plural': 'Количество вакансий',
            },
        ),
        migrations.AlterModelOptions(
            name='tablesalaryvacancies',
            options={'verbose_name': 'Средние зарплаты', 'verbose_name_plural': 'Средние зарплаты'},
        ),
    ]
