# Generated by Django 4.1.4 on 2023-01-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tablecountvacancies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableGeoSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=10000000, verbose_name='Город')),
                ('avgSalary', models.CharField(default='', max_length=100000, verbose_name='Уровень зарплат в рублях')),
            ],
            options={
                'verbose_name': 'З/п по городам',
                'verbose_name_plural': 'З/п по городам',
            },
        ),
    ]
