# Generated by Django 4.1.4 on 2023-01-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tablegeosalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablegeosalary',
            name='city',
            field=models.TextField(default='', verbose_name='Город'),
        ),
    ]
