# Generated by Django 4.1.4 on 2023-01-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tablegeosalary_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableGeoVac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(default='', verbose_name='Город')),
                ('proc', models.CharField(default='', max_length=100000, verbose_name='Доля вакансий в %')),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам',
                'verbose_name_plural': 'Доля вакансий городам',
            },
        ),
    ]
