# Generated by Django 4.1.4 on 2023-01-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tablegeovac'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=10000, verbose_name='Год')),
                ('skills', models.CharField(default='', max_length=100000, verbose_name='Топ 10 навыков')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
