# Generated by Django 4.1.4 on 2023-01-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tableskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableskills',
            name='skills',
            field=models.TextField(default='', verbose_name='Топ 10 навыков'),
        ),
    ]
