# Generated by Django 4.1.4 on 2023-01-11 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tableskills_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(default='0000', max_length=100)),
                ('name', models.CharField(default='name', max_length=100, verbose_name='Название вакансии')),
                ('published_at', models.DateTimeField(default=datetime.datetime(2023, 1, 7, 15, 10, 47, 625508), verbose_name='Дата публикации')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('key_skills', models.TextField(blank=True, null=True, verbose_name='Навыки')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Город')),
                ('url', models.URLField(max_length=100, null=True, verbose_name='Ссылка')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='зарплата')),
                ('employer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя нанимателя')),
            ],
            options={
                'verbose_name': 'Вакансии hh.ru',
                'verbose_name_plural': 'Вакансии hh.ru',
            },
        ),
    ]
