# Generated by Django 4.1.4 on 2023-01-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='title',
            field=models.CharField(default='Главная страница', max_length=100, verbose_name='Заголовок'),
        ),
    ]
